#fosun:
#  bddy:
#    http: http://bddy.fengyouhui.net
#  img:
#    http: http://img.fengyouhui.net
#  video:
#    http: http://video.fengyouhui.net
#  boss:
#    https: https://boss.fengyouhui.net
#  inquiry:
#    https: https://inquiry.fengyouhui.net
#  wx:
#    http: http://wx.fengyouhui.net
#  token:
#    https: https://boss-dev.fengyouhui.net
#  file:
#    http: http://download.fengyouhui.net
#    https: https://download.fengyouhui.net